spring:
  application:
    name: upload-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/studydb
    username: study
    password: study

server:
  port: 8002

aws:
  s3:
    bucket: studybuddy-materials
    region: us-east-1

minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket: materials
